electr_data <- read.table('household_power_consumption.txt', header = TRUE, sep = ';', na.strings = '?', stringsAsFactors = FALSE)
eldata <- subset(electr_data, Date %in% c('1/2/2007','2/2/2007'))
eldata$Date <- as.Date(eldata$Date, format = '%d/%m/%Y')
eldata$day <- paste(eldata$Date, eldata$Time)
library(lubridate)
eldata$day <- ymd_hms(eldata$day)
png('plot1.png')
hist(eldata$Global_active_power, xlab = 'Global Active Power (kilowatts)', ylab = 'Frequency', col = 'red', breaks = 12, main = 'Global Active Power')
dev.off()